units:
  # Proxy Spacing Variables
  # CHANGED: Updated to 19.05 for standard MX spacing
  kx: 19.05
  ky: 19.05
  # Padding Variables
  px: kx + 4
  py: ky + 4

  pushX: (kx / 2)
  pushY: (ky / 2)

  padX: pushX + 2
  padY: pushY + 2

  spacing: 0

points:
  zones:
    matrix:
      key:
        padding: 1ky + spacing
        spread: 1kx + spacing
      columns:
        outer:
          rows.mod.skip: false
          key:
            stagger: 0
            column_net: P011
        pinky:
          rows.mod.skip: false
          key:
            stagger: 0
            column_net: P100
        ring:
          key:
            stagger: 7
            column_net: P024
        middle:
          key:
            stagger: 5
            column_net: P022
        index:
          key:
            stagger: -6
            column_net: P020
        inner:
          rows:
            mod.skip: true
            bottom.skip: true
          key:
            stagger: -3
            column_net: P017
      rows:
        mod:
          row_net: P111
        bottom:
          row_net: P113
        home:
          row_net: P115
        top:
          row_net: P002
        num:
          row_net: P029
      anchor:
        shift: [100, -150]
    thumbs:
      key:
        padding: 1ky + spacing
        spread: 1.1kx + spacing
      anchor:
        ref: matrix_inner_mod
        shift: [2, -2]
      columns:
        layer:
          key:
            splay: -15
            column_net: P017
        space:
          key:
            splay: -5
            column_net: P031
      rows:
        cluster:
          row_net: P111
        other:
          row_net: P113
  mirror: &mirror
    ref: matrix_inner_num
    distance: 5kx

outlines:
  
  raw:
    - what: rectangle
      where: true
      size: [px, py]
  keys:
    - what: rectangle
      where: true
      size: [kx-0.7, ky-0.7]
      # size: [14, 14]
      fillet: 0

  rightboard:
    - what: polygon
      operation: stack
      fillet: 2
      points:
        - ref: mirror_matrix_inner_num
          shift: [0.5px, 0.5py]
        - ref: mirror_matrix_middle_num
          shift: [0.5px, 0.5py]
        - ref: mirror_matrix_middle_num
          shift: [-0.5px, 0.5py]
        - ref: mirror_matrix_ring_num
          shift: [-0.5px, 0.5py]
        - ref: mirror_matrix_outer_num
          shift: [-0.5px, 0.5py]
        - ref: mirror_matrix_outer_mod
          shift: [-0.5px, -0.5py]
        - ref: mirror_matrix_middle_mod
          shift: [0px, -1py]
        - ref: mirror_thumbs_layer_cluster
          shift: [-0.5px, -0.5py]
        - ref: mirror_thumbs_space_cluster
          shift: [0.5px, -0.5py]
        - ref: mirror_thumbs_space_other
          shift: [0.5px, 0.5px]
        - ref: mirror_matrix_inner_home
          shift: [0.5px, -0.2px]
    - what: rectangle
      where:
        ref: mirror_matrix_inner_num
        shift: [21, -21]      # Moved UP by ~21mm
        rotate: -90         # Rotated Horizontal
      size: [65, 18]
      expand: 3

  leftboard:
    - what: polygon
      operation: stack
      fillet: 2
      points:
        - ref: matrix_outer_num
          shift: [-0.5px, 0.5py]
        - ref: matrix_ring_num
          shift: [-0.5px, 0.5py]
        - ref: matrix_middle_num
          shift: [-0.5px, 0.5py]
        - ref: matrix_middle_num
          shift: [0.5px, 0.5py]
        - ref: matrix_inner_num
          shift: [0.5px, 0.5py]
        - ref: matrix_inner_home
          shift: [0.5px, -0.2px]
        - ref: thumbs_space_other
          shift: [0.5px, 0.5px]
        - ref: thumbs_space_cluster
          shift: [0.5px, -0.5py]
        - ref: thumbs_layer_cluster
          shift: [-0.5px, -0.5py]
        - ref: matrix_middle_mod
          shift: [0px, -1py]
        - ref: matrix_outer_mod
          shift: [-0.5px, -0.5py]
    - what: rectangle
      where:
        ref: matrix_inner_num
        shift: [21, -21]      # Moved UP by ~21mm
        rotate: -90         # Rotated Horizontal
      size: [65, 18]        # Swapped width/height to be horizontal
      expand: 3

  board:
    - what: polygon
      operation: stack
      fillet: 2
      points:
        - ref: matrix_outer_num
          shift: [-0.5px, 0.5py]
        - ref: matrix_ring_num
          shift: [-0.5px, 0.5py]
        - ref: matrix_middle_num
          shift: [-0.5px, 0.5py]
        - ref: matrix_middle_num
          shift: [0.5px, 0.5py]
        - ref: matrix_inner_num
          shift: [0.5px, 0.5py]
        - ref: mirror_matrix_inner_num
          shift: [0.5px, 0.5py]
        - ref: mirror_matrix_middle_num
          shift: [0.5px, 0.5py]
        - ref: mirror_matrix_middle_num
          shift: [-0.5px, 0.5py]
        - ref: mirror_matrix_ring_num
          shift: [-0.5px, 0.5py]
        - ref: mirror_matrix_outer_num
          shift: [-0.5px, 0.5py]
        - ref: mirror_matrix_outer_mod
          shift: [-0.5px, -0.5py]
        - ref: mirror_matrix_middle_mod
          shift: [0px, -1py]
        - ref: mirror_thumbs_layer_cluster
          shift: [-0.5px, -0.5py]
        - ref: mirror_thumbs_space_cluster
          shift: [0.75px, -0.5py]
        - ref: thumbs_space_cluster
          shift: [0.75px, -0.5py]
        - ref: thumbs_layer_cluster
          shift: [-0.5px, -0.5py]
        - ref: matrix_middle_mod
          shift: [0px, -1py]
        - ref: matrix_outer_mod
          shift: [-0.5px, -0.5py]

  combobody:
    - name: board
    - operation: subtract
      name: keys
  comboleft:
    - name: leftboard
    - operation: subtract
      name: keys
  comboright:
    - name: rightboard
    - operation: subtract
      name: keys

  plate_hole:
    - what: rectangle
      where: true
      size: 14
      fillet: 0
  plate_left:
    - name: leftboard
      expand: 3        
    - name: plate_hole
      operation: subtract
  plate_right:
    - name: rightboard
      expand: 3
    - name: plate_hole
      operation: subtract

pcbs:
  left:
    outlines:
      main:
        outline: leftboard
    footprints:
      choc_hotswap:
        # CHANGED: Switched to MX Hybrid footprint
        what: hybrid
        where: /^(matrix_|thumbs_).*/
        params:
          P1: "{{colrow}}"
          P2: "{{column_net}}"
        adjust:
          rotate: 180

      # Micro Controller
      nice_nano:
        what: nice_nano
        params:
          orientation: up
        where:
          ref: matrix_inner_num
          shift: [21, -4]   
          rotate: -90

      # Battery Jack
      jstph:
        what: jstph
        where:
          ref: matrix_inner_num
          shift: [21, -10.5]
          rotate: 90
        params:
          side: B
          pos: pos
          neg: GND

      horizontal_reset:
        what: side_switch_TSA002
        params:
          side: B
          from: GND
          to: RST
        where:
          ref: matrix_inner_num
          shift: [-10, 17.5]
          rotate: -14
      
      battery_switch:
        what: power_switch_smd_side
        where:
          ref: matrix_inner_num
          shift: [0, 15.2]
          rotate: 76
        params:
          side: B
          from: pos
          to: RAW
       
      hole_center:
        what: mountinghole
        where:
          ref: matrix_middle_bottom
          shift: [-pushX, pushY]

      hole_new:
        what: mountinghole
        where:
          ref: matrix_middle_bottom
          shift: [-pushX, pushY]

      default_diode:
        what: diode
        where: /^(matrix_|thumbs_).*/
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [0.8, -10.0]
          rotate: 180
      # weird_diode:
      #   what: diode
      #   where: /^(matrix_(?:outer_|ring_|index_(?!(?:top))|pinky_)).*/
      #   params:
      #     from: "{{colrow}}"
      #     to: "{{row_net}}"
      #   adjust:
      #     shift: [0, 6.0]
      #     rotate: -180
      # martixindextop:
      #   what: diode
      #   where: /^(matrix_index_(?:top)).*/
      #   params:
      #     from: "{{colrow}}"
      #     to: "{{row_net}}"
      #   adjust:
      #     shift: [7.68, -3.0]
      #     rotate: 90
      front_text: &text
        what: text
        where: &textWhere
            ref: matrix_middle_mod
            shift: [-26.7, -17.5]
        params: &textParams
            text: SBBoardv2
            justify: left
            h_size: 3.0
            v_size: 3.0
            thickness: 0.4

  right:
    outlines:
      main:
        outline: rightboard
    footprints:
      choc_hotswap:
        what: hybrid
        where: /^(mirror_matrix_|mirror_thumbs_).*/
        params:
          P1: "{{colrow}}"
          P2: "{{column_net}}"
        adjust:
          rotate: 180
      # Micro Controller
      nice_nano:
        what: nice_nano
        params:
          orientation: up
        where:
          ref: mirror_matrix_inner_num
          shift: [21, -4]   
          rotate: 90

      # Battery Jack
      jstph:
        what: jstph
        where:
          ref: mirror_matrix_inner_num
          shift: [21, -10.5]
          rotate: 90
        params:
          side: B
          pos: pos
          neg: GND

      horizontal_reset:
        what: side_switch_TSA002
        params:
          side: B
          from: GND
          to: RST
        where:
          ref: mirror_matrix_inner_num
          shift: [-10, 17.5]
          rotate: -14.0

      
      # Battery on/off switch
      battery_switch_2:
        what: power_switch_smd_side
        where:
          ref: mirror_matrix_inner_num
          shift: [0, 15.2]
          rotate: -104
        params:
          side: B
          from: pos
          to: RAW
           
      hole_center:
        what: mountinghole
        where:
          ref: mirror_matrix_middle_bottom
          shift: [-pushX, pushY - 4]

      default_diode:
        what: diode
        where: /^(mirror_matrix_|mirror_thumbs_).*/
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [0.8, -9.0]
          rotate: 180
          # rotate: 90
      # weird_diode:
      #   what: diode
      #   where: /^(mirror_matrix_(?:outer_|ring_|pinky_)).*/
      #   params:
      #     from: "{{colrow}}"
      #     to: "{{row_net}}"
      #   adjust:
      #     shift: [0, 5.0]
      #     rotate: 180
      front_text: &text
        what: text
        where: &textWhere
            ref: mirror_matrix_middle_mod
            shift: [-2.7, -17.5]
        params: &textParams
            text: SBBoardv2
            justify: left
            h_size: 3.0
            v_size: 3.0
            thickness: 0.4
cases:
  left_plate:
    - name: plate_left
      extrude: 1.5
  right_plate:
    - name: plate_right
      extrude: 1.5